<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class DatabaseSeeder extends Seeder
{ 
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now('America/Bogota');
        DB::table('users')->insert([
            'id' => 1,
            'name' => 'administrador',
            'email' => 'proyectowebchronos@gmail.com',
            'password' => bcrypt('admin'),
            'type'=>'admin',
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('users')->insert([
            'id' => 2,
            'name' => 'ana maria',
            'email' => 'anamaria@gmail.com',
            'password' => bcrypt('admin'),
            'type'=>'advisor',
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('users')->insert([
            'id' => 7,
            'name' => 'manuela',
            'email' => 'manuela@gmail.com',
            'password' => bcrypt('admin'),
            'type'=>'advisor',
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('users')->insert([
            'id' => 3,
            'name' => 'jose alberto',
            'email' => 'jose@gmail.com',
            'password' => bcrypt('admin'),
            'type'=>'technical',
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('users')->insert([
            'id' => 4,
            'name' => 'david',
            'email' => 'david@gmail.com',
            'password' => bcrypt('admin'),
            'type'=>'sales_manager',
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('users')->insert([
            'id' => 5,
            'name' => 'andrea',
            'email' => 'andrea@gmail.com',
            'password' => bcrypt('admin'),
            'type'=>'marketing_manager',
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('users')->insert([
            'id' => 6,
            'name' => 'eilyn',
            'email' => 'eilyn@gmail.com',
            'password' => bcrypt('admin'),
            'type'=>'customer_service_manager',
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('users')->insert([
            'id' => 8,
            'name' => 'administrador',
            'email' => 'angela@gmail.com',
            'password' => bcrypt('admin'),
            'type'=>'admin',
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('users')->insert([
            'id' => 9,
            'name' => 'luis',
            'email' => 'luis@gmail.com',
            'password' => bcrypt('admin'),
            'type'=>'advisor',
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('users')->insert([
            'id' => 10,
            'name' => 'pedro',
            'email' => 'pedro@gmail.com',
            'password' => bcrypt('admin'),
            'type'=>'advisor',
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('users')->insert([
            'id' => 11,
            'name' => 'luisa',
            'email' => 'luisa@gmail.com',
            'password' => bcrypt('admin'),
            'type'=>'advisor',
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('users')->insert([
            'id' => 12,
            'name' => 'camila',
            'email' => 'camila@gmail.com',
            'password' => bcrypt('admin'),
            'type'=>'advisor',
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('products')->insert([
            'id' => 1,
            'name' => 'computador',
            'stock_min' => 1,
            'cantidad' => 50,
            'precio_fabrica' => 1200000,
            'precio_venta' => 2000000,
            'descripcion' => 'computador intel celeron',
            'flag' => 1,
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('products')->insert([
            'id' => 2,
            'name' => 'memoria ram',
            'stock_min' => 1,
            'cantidad' => 20,
            'precio_fabrica' => 50000,
            'precio_venta' => 80000,
            'descripcion' => 'memoria ram 8gb',
            'flag' => 1,
            'created_at'=>$now,
            'updated_at'=>$now,
            
        ]); 
        DB::table('products')->insert([
            'id' => 3,
            'name' => 'mantenimiento',
            'stock_min' => null,
            'cantidad' => null,
            'precio_fabrica' => null,
            'precio_venta' => 60000,
            'descripcion' => 'mantenimiento de computador',
            'flag' => 0,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]); 
        DB::table('clients')->insert([
            'id' => 1,
            'name' => 'anastasia',
            'user_id' => 2,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'calle falsa 123',
            'telefono' => '555555',
            'sexo' => 'femenino',
            'cedula' => '1065627510',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos1@gmail.com',
            'comentarios' => 'sabe respirar muy bien',
            'oportunidad' => 1,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 2,
            'name' => 'brayan',
            'user_id' => 2,
            'estado' => 'cliente',
            'tipo' => 'persona',
            'direccion' => 'calle falsa 123',
            'telefono' => '555555',
            'sexo' => 'masculino',
            'cedula' => '1065627511',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos2@gmail.com',
            'comentarios' => 'sabe respirar muy bien',
            'oportunidad' => 2,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 3,
            'name' => 'pepito',
            'user_id' => 2,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'calle falsa 123',
            'telefono' => '555555',
            'sexo' => 'masculino',
            'cedula' => '1065627512',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos3@gmail.com',
            'comentarios' => 'sabe respirar muy bien',
            'oportunidad' => 3,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 4,
            'name' => 'eustaquio',
            'user_id' => 2,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'calle falsa 123',
            'telefono' => '555555',
            'sexo' => 'masculino',
            'cedula' => '1065627513',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos4@gmail.com',
            'comentarios' => 'sabe respirar muy bien',
            'oportunidad' => 1,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 5,
            'name' => 'maria',
            'user_id' => 2,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'calle falsa 123',
            'telefono' => '555555',
            'sexo' => 'masculino',
            'cedula' => '1065627514',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos5@gmail.com',
            'comentarios' => 'sabe respirar muy bien',
            'oportunidad' => 2,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 6,
            'name' => 'liliana',
            'user_id' => 2,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'calle falsa 123',
            'telefono' => '555555',
            'sexo' => 'masculino',
            'cedula' => '1065627515',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos6@gmail.com',
            'comentarios' => 'sabe respirar muy bien',
            'oportunidad' => 3,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 7,
            'name' => 'andres',
            'user_id' => 2,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'calle falsa 123',
            'telefono' => '555555',
            'sexo' => 'masculino',
            'cedula' => '1065627516',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos7@gmail.com',
            'comentarios' => 'sabe respirar muy bien',
            'oportunidad' => 1,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 8,
            'name' => 'manuelo',
            'user_id' => 7,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'calle falsa 123',
            'telefono' => '555555',
            'sexo' => 'masculino',
            'cedula' => '1065627517',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos8@gmail.com',
            'comentarios' => 'sabe respirar muy bien',
            'oportunidad' => 2,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 9,
            'name' => 'cliente david',
            'user_id' => 4,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'calle falsa 123',
            'telefono' => '555555',
            'sexo' => 'masculino',
            'cedula' => '1065627517',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos9@gmail.com',
            'comentarios' => 'sabe respirar muy bien',
            'oportunidad' => 3,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 10,
            'name' => 'referido cliente david',
            'user_id' => 4,
            'estado' => 'cliente',
            'tipo' => 'persona',
            'direccion' => 'calle falsa 123',
            'telefono' => '555555',
            'sexo' => 'masculino',
            'cedula' => '1065627518',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos10@gmail.com',
            'comentarios' => 'sabe respirar muy bien',
            'oportunidad' => 1,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 11,
            'name' => 'melisa',
            'user_id' => 10,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'carrera 47',
            'telefono' => '21548',
            'sexo' => 'femenino',
            'cedula' => '1065627519',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos11@gmail.com',
            'comentarios' => '',
            'oportunidad' => 2,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 12,
            'name' => 'rodolfo',
            'user_id' => 10,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'carrera 38',
            'telefono' => '21549',
            'sexo' => 'masculino',
            'cedula' => '1065627520',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos12@gmail.com',
            'comentarios' => '',
            'oportunidad' => 3,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 13,
            'name' => 'antonieta',
            'user_id' => 10,
            'estado' => 'cliente',
            'tipo' => 'persona',
            'direccion' => 'carrera 56',
            'telefono' => '21550',
            'sexo' => 'femenino',
            'cedula' => '1065627521',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos13@gmail.com',
            'comentarios' => '',
            'oportunidad' => 1,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 14,
            'name' => 'cristobal',
            'user_id' => 10,
            'estado' => 'cliente',
            'tipo' => 'persona',
            'direccion' => 'carrera 120',
            'telefono' => '21551',
            'sexo' => 'masculino',
            'cedula' => '1065627522',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos14@gmail.com',
            'comentarios' => '',
            'oportunidad' => 2,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 15,
            'name' => 'norma',
            'user_id' => 10,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'carrera 90',
            'telefono' => '21552',
            'sexo' => 'femenino',
            'cedula' => '1065627523',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos15@gmail.com',
            'comentarios' => '',
            'oportunidad' => 1,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 16,
            'name' => 'lumer',
            'user_id' => 9,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'carrera 91',
            'telefono' => '21553',
            'sexo' => 'masculino',
            'cedula' => '1065627524',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos16@gmail.com',
            'comentarios' => '',
            'oportunidad' => 2,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 17,
            'name' => 'alonso',
            'user_id' => 9,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'carrera 83',
            'telefono' => '21554',
            'sexo' => 'masculino',
            'cedula' => '1065627525',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos17@gmail.com',
            'comentarios' => '',
            'oportunidad' => 3,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 18,
            'name' => 'cecilia',
            'user_id' => 9,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'carrera 77',
            'telefono' => '21555',
            'sexo' => 'femenino',
            'cedula' => '1065627526',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos18@gmail.com',
            'comentarios' => '',
            'oportunidad' => 1,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 19,
            'name' => 'malena',
            'user_id' => 9,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'carrera 77',
            'telefono' => '21556',
            'sexo' => 'femenino',
            'cedula' => '1065627527',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos19@gmail.com',
            'comentarios' => '',
            'oportunidad' => 2,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 20,
            'name' => 'colegio universal',
            'user_id' => 9,
            'estado' => 'prospecto',
            'tipo' => 'empresa',
            'direccion' => 'transversal 72',
            'telefono' => '21557',
            'sexo' => 'femenino',
            'cedula' => '1065627528',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos20@gmail.com',
            'comentarios' => '',
            'oportunidad' => 3,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 21,
            'name' => 'mariana',
            'user_id' => 11,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'carrera 123',
            'telefono' => '21558',
            'sexo' => 'femenino',
            'cedula' => '1065627529',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos21@gmail.com',
            'comentarios' => '',
            'oportunidad' => 1,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 22,
            'name' => 'juana',
            'user_id' => 11,
            'estado' => 'cliente',
            'tipo' => 'persona',
            'direccion' => 'carrera 26',
            'telefono' => '21559',
            'sexo' => 'femenino',
            'cedula' => '1065627530',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos22@gmail.com',
            'comentarios' => '',
            'oportunidad' => 2,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('clients')->insert([
            'id' => 23,
            'name' => 'amador',
            'user_id' => 12,
            'estado' => 'prospecto',
            'tipo' => 'persona',
            'direccion' => 'carrera 561',
            'telefono' => '21560',
            'sexo' => 'masculino',
            'cedula' => '1065627531',
            'whatsapp' => 'false',
            'email' => 'proyectowebchronos23@gmail.com',
            'comentarios' => '',
            'oportunidad' => 3,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('Referreds')->insert([
            'id' => 1,            
            'client_id' => 1,
            'padre_id' => 4,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('Referreds')->insert([
            'id' => 2,            
            'client_id' => 4,
            'padre_id' => 5,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('Referreds')->insert([
            'id' => 3,            
            'client_id' => 4,
            'padre_id' => 6,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('Referreds')->insert([
            'id' => 4,            
            'client_id' => 6,
            'padre_id' => 7,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
        DB::table('Referreds')->insert([
            'id' => 5,            
            'client_id' => 9,
            'padre_id' => 10,
            'created_at'=>$now,
            'updated_at'=>$now,            
        ]);
//        DB::table('events')->insert([
//            'id' => 1,
//            'asunto' => 'visita conjunto cerrado mango maduro',
//            'informacion' =>  'queda ubicado en calle verdadera al lado de una casa con ventanas',
//            'hora' => '08:08:24',
//            'fecha' => '2017-07-20',            
//        ]);
//        DB::table('event_user')->insert([
//            'id' => 1,
//            'user_id' => 1,
//            'event_id' =>  1,  
//            'created_at'=>$now,
//            'updated_at'=>$now,            
//        ]);
        DB::table('tickets')->insert([
            'id' => 1,
            'caso' => 'mantenimiento',
            'estado' => 'pendiente',
            'descripcion'=>'muy descriptiva',
            'prioridad'=> 1,
            'client_id' =>  2,     
//            'product_id' =>  1,     
            'user_id' =>  3,  
            'created_at'=>$now,
            'updated_at'=>$now,
            
        ]);
        DB::table('tickets')->insert([
            'id' => 2,
            'caso' => 'mantenimiento',
            'estado' => 'resuelto',
            'descripcion'=>'muy descriptiva',
            'prioridad'=> 2,
            'client_id' =>  2,     
//            'product_id' =>  1,     
            'user_id' =>  3, 
            'created_at'=>$now,
            'updated_at'=>$now,
            
        ]);
        DB::table('tickets')->insert([
            'id' => 3,
            'caso' => 'mantenimiento',
            'estado' => 'pendiente',
            'descripcion'=>'muy descriptiva',
            'prioridad'=> 3,
            'client_id' =>  2,     
//            'product_id' =>  1,     
            'user_id' =>  3, 
            'created_at'=>$now,
            'updated_at'=>$now,
            
        ]);
        DB::table('tickets')->insert([
            'id' => 4,
            'caso' => 'mantenimiento',
            'estado' => 'descartado',
            'descripcion'=>'muy descriptiva',
            'prioridad'=> 1,
            'client_id' =>  2,     
//            'product_id' =>  1,     
            'user_id' =>  3, 
            'created_at'=>$now,
            'updated_at'=>$now,
            
        ]);
        DB::table('product_ticket')->insert([
            'id' => 1,
            'ticket_id' => 1,    
            'product_id' =>  1,
            'created_at'=>$now,
            'updated_at'=>$now, 
        ]);
        DB::table('product_ticket')->insert([
            'id' => 2,
            'ticket_id' => 2,    
            'product_id' =>  1,
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('product_ticket')->insert([
            'id' => 3,
            'ticket_id' => 2,    
            'product_id' =>  2,  
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('product_ticket')->insert([
            'id' => 4,
            'ticket_id' => 2,    
            'product_id' =>  3,  
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('negotiations')->insert([
            'id' => 1,
            'estado' => 'en proceso',
            'detalles' =>  'esta esperando que el pagadiario le de el prestamo',   
            'forma_pago' => 'decontado', 
            'total_negociacion'=> 15000,
            'cierre' =>  'null',     
            'client_id' =>  1,     
//            'product_id' =>  1,     
            'user_id' =>  2,   
            'created_at'=>$now,
            'updated_at'=>$now,
            
        ]);
        DB::table('negotiations')->insert([
            'id' => 2,
            'estado' => 'perdida',
            'detalles' =>  'esta esperando que el pagadiario le de el prestamo',   
            'forma_pago' => 'decontado', 
            'total_negociacion'=> 45000,
            'cierre' =>  'null',     
            'client_id' =>  3,     
//            'product_id' =>  1,     
            'user_id' =>  2,   
            'created_at'=>$now,
            'updated_at'=>$now,
            
        ]);
        DB::table('negotiations')->insert([
            'id' => 3,
            'estado' => 'ganada',
            'detalles' =>  'esta esperando que el pagadiario le de el prestamo',   
            'forma_pago' => 'decontado', 
            'total_negociacion'=> 15000,
            'cierre' =>  'null',     
            'client_id' =>  2,     
//            'product_id' =>  1,     
            'user_id' =>  2,  
            'created_at'=>$now,
            'updated_at'=>$now,
            
        ]);
        DB::table('negotiations')->insert([
            'id' => 4,
            'estado' => 'en proceso',
            'detalles' =>  'esta esperando que el pagadiario le de el prestamo',   
            'forma_pago' => 'decontado', 
            'total_negociacion'=> 15000,
            'cierre' =>  'null',     
            'client_id' =>  9,     
//            'product_id' =>  1,     
            'user_id' =>  4,  
            'created_at'=>$now,
            'updated_at'=>$now,
            
        ]);
        DB::table('negotiations')->insert([
            'id' => 5,
            'estado' => 'ganada',
            'detalles' =>  'esta esperando que el pagadiario le de el prestamo',   
            'forma_pago' => 'decontado', 
            'total_negociacion'=> 15000,
            'cierre' =>  'null',     
            'client_id' =>  10,     
//            'product_id' =>  1,     
            'user_id' =>  4,  
            'created_at'=>$now,
            'updated_at'=>$now,
            
        ]);
        DB::table('negotiations')->insert([
            'id' => 6,
            'estado' => 'en proceso',
            'detalles' =>  'venta de computador',   
            'forma_pago' => 'decontado', 
            'total_negociacion'=> 2000000,
            'cierre' =>  'null',     
            'client_id' =>  17,     
//            'product_id' =>  1,     
            'user_id' =>  9,  
            'created_at'=>$now,
            'updated_at'=>$now,
            
        ]);
        DB::table('negotiations')->insert([
            'id' => 7,
            'estado' => 'ganada',
            'detalles' =>  'venta de computador',   
            'forma_pago' => 'decontado', 
            'total_negociacion'=> 2000000,
            'cierre' =>  'null',     
            'client_id' =>  13,     
//            'product_id' =>  1,     
            'user_id' =>  10,  
            'created_at'=>$now,
            'updated_at'=>$now,
            
        ]);
        DB::table('negotiations')->insert([
            'id' => 8,
            'estado' => 'ganada',
            'detalles' =>  'venta de computador',   
            'forma_pago' => 'decontado', 
            'total_negociacion'=> 2000000,
            'cierre' =>  'null',     
            'client_id' =>  14,     
//            'product_id' =>  1,     
            'user_id' =>  10,  
            'created_at'=>$now,
            'updated_at'=>$now,
            
        ]);
        DB::table('negotiations')->insert([
            'id' => 9,
            'estado' => 'ganada',
            'detalles' =>  'venta de ram',   
            'forma_pago' => 'decontado', 
            'total_negociacion'=> 80000,
            'cierre' =>  'null',     
            'client_id' =>  22,     
//            'product_id' =>  1,     
            'user_id' =>  11,  
            'created_at'=>$now,
            'updated_at'=>$now,
            
        ]);
        DB::table('negotiation_product')->insert([
            'id' => 1,
            'negotiation_id' => 1,    
            'product_id' =>  1, 
            'cantidad' =>  1, 
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('negotiation_product')->insert([
            'id' => 2,
            'negotiation_id' => 2,    
            'product_id' =>  1,
            'cantidad' =>  1, 
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('negotiation_product')->insert([
            'id' => 3,
            'negotiation_id' => 2,    
            'product_id' =>  2,
            'cantidad' =>  1, 
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('negotiation_product')->insert([
            'id' => 4,
            'negotiation_id' => 2,    
            'product_id' =>  3,
            'cantidad' =>  0,  
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('negotiation_product')->insert([
            'id' => 5,
            'negotiation_id' => 3,    
            'product_id' =>  2,
            'cantidad' =>  1, 
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('negotiation_product')->insert([
            'id' => 6,
            'negotiation_id' => 4,    
            'product_id' =>  2,
            'cantidad' =>  1, 
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('negotiation_product')->insert([
            'id' => 7,
            'negotiation_id' => 6,    
            'product_id' =>  1,
            'cantidad' =>  1, 
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('negotiation_product')->insert([
            'id' => 8,
            'negotiation_id' => 7,    
            'product_id' =>  1,
            'cantidad' =>  1, 
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('negotiation_product')->insert([
            'id' => 9,
            'negotiation_id' => 8,    
            'product_id' =>  1,
            'cantidad' =>  1, 
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
        DB::table('negotiation_product')->insert([
            'id' => 10,
            'negotiation_id' => 9,    
            'product_id' =>  2,
            'cantidad' =>  1, 
            'created_at'=>$now,
            'updated_at'=>$now,
        ]);
    }
}
